name: CI

on:  
  push:
    tags:
      - '*'

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up dapper
        with:
          image: golang
          tag: latest
          run: go run main.go